### ISSUE TITLE
feature: popover for dataset filters

### ISSUE THREAD

**Issue by kmkhami** [arguflow/vault#7]
bonus: make the filters searchable via combobox. This will become relevant if we continue to download the weekly updates for the various folders.

- [x] checkbox for every dataset
- [x] text input for requirement on a string to be contained in the URL
- [x] bonus: combobox for searching through datasets. If we add weekly updates, we'll need this
- [x] put filters into URL and pull them from URL on the /search page

**Comment by kmkhami** [comment]
$20 for basic popover with filter checkboxes
$30 for popover with combobox

**Comment by densumesh** [comment]
@kmkhami what do you mean by text input for requirement on a string to be contained in the URL?
